In [1]:
import numpy as np

In [17]:
a = np.arange(5)

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a + 10

array([10, 11, 12, 13])

In [8]:
a * 10

array([ 0, 10, 20, 30])

In [9]:
a

array([0, 1, 2, 3])

In [15]:
a += 100

In [16]:
a

array([600, 601, 602, 603])